spring:
  application:
    name: store
  profiles:
    active: dev
  datasource:
    url: ${spring.datasource.URL}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    show-sql: true