spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_DATABASE:}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true